defaults: &defaults
  adapter: mysql2
  encoding: utf8
  username: root
  password: root
  #socket: /opt/local/var/run/mysql5/mysqld.sock

development:
  database: iforum_development
  <<: *defaults

test:
  database: iforum_test 
  <<: *defaults

production:
  database: blog_production
  <<: *defaults

